# Generated by Django 3.2.9 on 2021-12-24 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stock_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='sign',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='currency',
            name='ticker',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='stock',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.currency'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
